[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bpod-rig"
version = "0.0.2"
description = "Python software suite for Bpod, built around int-brain-lab's bpod-core"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Joshua Sanders", email = "josh@sanworks.io" },
    { name = "Austin Pauley", email = "pauley@psy.fsu.edu" },
    { name = "Florian Rau", email = "bimac@users.noreply.github.com" },
    { name = "Steven Smith", email = "steven@stevenlsmith.com" },
    { name = "George Stuyt", email = "george.stuyt@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "bpod-core==0.1.0a12",
    "platformdirs>=4.5.1",
    "pydantic==2.11.7",
    "typer>=0.25.1",
]

[project.optional-dependencies]
test = ["pytest>=9.0.2"]

[project.urls]
Changelog = "https://github.com/sanworks/bpod-rig/blob/main/CHANGELOG.md"
# Documentation = "https://int-brain-lab.github.io/bpod-core/"
Homepage = "https://github.com/sanworks/bpod-rig"
Issues = "https://github.com/sanworks/bpod-rig/issues"
Repository = "https://github.com/sanworks/bpod-rig.git"

[tool.setuptools.packages]
find = { where = [""], include = ["*", "examples", "tests"] }
# We want to include the examples folder in the wheel incase its needed
# We need to explicitly include examples as it is a reserved name
# We also include tests so users can verify installation on their systems

[project.scripts]
bpod = "bpod_rig.__main__:main"

[tool.uv]
exclude-newer = "2 weeks"
exclude-newer-package = { bpod-core = false }
required-version = ">=0.11.15"

[tool.pyright]
venvPath = "."
venv = ".venv"


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".egg-info",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "A",    # flake8-builtins
    "ANN",  # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "D",    # pydocstyle
    "E",    # pycodestyle Error
    "F",    # Pyflakes
    "FA",   # flake8-future-annotations
    "FBT",  # flake8-boolean-trap
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "N",    # pep8-naming
    "NPY",  # NumPy-specific rules
    "PERF", # Perflint
    "PIE",  # flake8-pie
    "PL",   # pylint
    "PTH",  # flake8-use-pathlib
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "T20",  # flake8-print
    "TID",  # flake8-tidy-imports
    "TC",   # flake8-type-checking
    "TRY",  # tryceratops
    "UP",   # pyupgrade
    "W",    # pycodestyle Warning
]

ignore = [
    "COM812",  # Missing trailing comma
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D205",    # 1 blank line required between summary line and description
    "D401",    # First line of docstring should be in imperative mood
    "PERF401", # Prefer list comprehension over for loop
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
    "RET504",  # Unnecessary assignment to variable (e.g., `return x` instead of `x = ...; return x`)
    "S101",    # Use of assert
    "T201",    # print found
    "TRY003",  # Avoid specifying long messages outside the exception class
]

# Allow fix for all enabled rules (when `--fix`) is provided.
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"!tests/**.py" = [
    "PT",     # flake8-pytest-style
]
"tests/**.py" = [
    "ANN201", # Missing type annotation for return in public function
    "ARG001", # Unused function argument
    "ARG002", # Unused method argument
    "PERF",   # Perflint
    "S101",   # Use of assert detected
    "S104",   # Possible binding to all interfaces
    "SLF001", # private-member-access
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[dependency-groups]
dev = [{ include-group = "test" }]
docs = [
    "myst-parser>=4.0.1",
    "sphinx>=8.1.3",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-autodoc-typehints>=3.0.1",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.6.1",
    "sphinx-github-style>=1.2.2",
    "sphinx-jsonschema>=1.19.2",
    "sphinx-rtd-dark-mode>=1.3.0",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx-toolbox>=4.0.0",
    ]
test = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.4",
    "pyright>=1.1.408",
]

[tool.pytest.ini_options]
log_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(name)s: %(message)s"
log_date_format = "%H:%M:%S"
log_file = "pytest.log"
log_file_level = "DEBUG"
