name: Tests
# Tests for Pull Requests that give results quickly.
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # astral-sh/setup-uv@8.1.0
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      # Use a cache to rapidly access known uv lockfiles.
      - name: Cache uv dependencies
      # actions/cache@v5.0.5
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
            path: |
                ~/.cache/uv
                .venv
            key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
            restore-keys: |
                ${{ runner.os }}-uv-

      # Use Python version that is the primary support version.
      - name: Set up Python
      # actions/setup-python@v6.2.0
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"

      - name: Run checks and tests with coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            uv sync --locked --all-extras
            uv run ruff check .
            uv run pyright .
            uv run python -m pytest --cov --cov-report=xml

      - name: Upload coverage to Coveralls
      # coverallsapp/github-action@v2.3.6
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        with:
          file: coverage.xml
          parallel: false
